spring.application.name=rbac-system
spring.datasource.url=jdbc:mysql://localhost:3306/rbac_system
spring.datasource.username=root
spring.datasource.password=kha512020
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.secret-key=2ee1168c42cab38b7f712dd022fe42de61be2f61326544facdb3d345f93276f6
jwt.expiration-time=3600000